# Generated by Django 5.2.7 on 2025-11-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='التصنيف',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_التصنيف', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('وصف', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='المنتج',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('اسم_المنتج', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('الوصف', models.TextField(verbose_name='الوصف')),
                ('السعر', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
                ('الصورة', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('متوفر', models.BooleanField(default=True, verbose_name='متوفر؟')),
                ('تاريخ_الإضافة', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('التصنيف', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='المنتجات', to='store.التصنيف', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
    ]
