# Generated by Django 5.2.7 on 2025-11-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_الطلب_طلب_rename_عنصر_الطلب_عنصر_طلب'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='التصنيف',
            new_name='تصنيف',
        ),
        migrations.RenameModel(
            old_name='المنتج',
            new_name='منتج',
        ),
    ]
