# Generated by Django 5.2.7 on 2025-11-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_التصنيف_تصنيف_rename_المنتج_منتج'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر')),
                ('image', models.ImageField(upload_to='products/', verbose_name='صورة المنتج')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.RemoveField(
            model_name='منتج',
            name='التصنيف',
        ),
        migrations.DeleteModel(
            name='تصنيف',
        ),
    ]
