# Generated by Django 5.2.7 on 2025-11-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_عنصر_طلب_المنتج'),
        ('store', '0003_product_remove_منتج_التصنيف_delete_تصنيف'),
    ]

    operations = [
        migrations.DeleteModel(
            name='منتج',
        ),
    ]
