# Generated by Django 5.2.7 on 2025-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=100, verbose_name='اسم المرسل')),
                ('البريد_الإلكتروني', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('الموضوع', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('الرسالة', models.TextField(verbose_name='نص الرسالة')),
                ('تاريخ_الإرسال', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
            },
        ),
    ]
