# Generated by Django 5.2.7 on 2025-11-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='رسالة_تواصل',
        ),
    ]
