# Generated by Django 5.2.7 on 2025-11-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='الطلب',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('البريد_الإلكتروني', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('رقم_الهاتف', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('العنوان', models.TextField(verbose_name='عنوان التوصيل')),
                ('تاريخ_الطلب', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('مكتمل', models.BooleanField(default=False, verbose_name='تم التنفيذ؟')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
            },
        ),
        migrations.CreateModel(
            name='عنصر_الطلب',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الكمية', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('الطلب', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='العناصر', to='orders.الطلب', verbose_name='الطلب')),
                ('المنتج', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.المنتج', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
    ]
