# Generated by Django 5.2.7 on 2025-11-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='الطلب',
            new_name='طلب',
        ),
        migrations.RenameModel(
            old_name='عنصر_الطلب',
            new_name='عنصر_طلب',
        ),
    ]
