# Generated by Django 5.2.7 on 2025-11-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_الطلب_طلب_rename_عنصر_الطلب_عنصر_طلب'),
    ]

    operations = [
        migrations.AlterField(
            model_name='عنصر_طلب',
            name='الطلب',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='عناصر_الطلب', to='orders.طلب', verbose_name='الطلب'),
        ),
    ]
