# Generated by Django 5.2.7 on 2025-11-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_عنصر_طلب_الطلب'),
        ('store', '0003_product_remove_منتج_التصنيف_delete_تصنيف'),
    ]

    operations = [
        migrations.AlterField(
            model_name='عنصر_طلب',
            name='المنتج',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج'),
        ),
    ]
